export async function getLeftMenuData() {
  return [
    {
      title: 'Tổng quan',
      key: 'category',
      url: ['/tong-quan'],
      icon: 'icon icon-dashboard',
      permission: [],
      pro: true,
    },
    {
      title: 'Booking',
      key: 'booking',
      url: ['/booking', '/booking/:id/chi-tiet'],
      icon: 'icon icon-laptop',
      permission: [],
      pro: true,
    },
    {
      title: 'Danh sách nơi lưu trú',
      key: 'items',
      url: [
        '/danh-sach-noi-luu-tru',
        '/danh-sach-noi-luu-tru/tao-moi',
        '/danh-sach-noi-luu-tru/:id/chi-tiet',
      ],
      icon: 'icon icon-laptop',
      permission: [],
      pro: true,
    },
    {
      title: 'Danh sách gói dịch vụ',
      key: 'services',
      url: [
        '/danh-sach-goi-dich-vu',
        '/danh-sach-goi-dich-vu/tao-moi',
        '/danh-sach-goi-dich-vu/:id/chi-tiet',
      ],
      icon: 'icon icon-agenda',
      permission: [],
      pro: true,
    },
    {
      title: 'Chuyến đi của bạn',
      key: 'goal',
      url: ['/chuyen-di-cua-ban'],
      icon: 'icon icon-goal',
      permission: [],
      pro: true,
    },
    {
      title: 'Hồ sơ',
      key: 'info',
      url: [
        '/ho-so/chinh-sua',
        '/ho-so/tin-tuong-va-xac-minh',
        '/ho-so/danh-gia-ve-ban',
        '/ho-so/hinh-anh',
      ],
      icon: 'icon icon-videoconference',
      permission: [],
      pro: true,
    },
    {
      title: 'Tài khoản',
      key: 'account',
      url: ['/tai-khoan'],
      icon: 'icon icon-profits',
      permission: [],
      pro: true,
    },
    {
      title: 'Tín dụng du lịch',
      key: 'payment',
      url: ['/tin-dung-du-lich'],
      icon: 'icon icon-wallet',
      permission: [],
      pro: true,
    },
    {
      title: 'Tranh chấp',
      key: 'diploma',
      url: ['/tranh-chap'],
      icon: 'icon icon-diploma',
      permission: [],
      pro: true,
    },
  ];
}
